CAN_DIAMETER_WIDEST=66.04; //2.60 inches
CAN_RADIUS_WIDEST=CAN_DIAMETER_WIDEST/2;
CAN_HEIGHT=122.682; //4.83 inches
CAN_EXTRUDED_HEIGHT=CAN_HEIGHT + 20;

module can_extrusion() {
    cylinder(r=CAN_RADIUS_WIDEST, h=CAN_EXTRUDED_HEIGHT, $fn=100);
}
